FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

WORKDIR /app

COPY services/embedding_api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY services/embedding_api/app ./app
COPY services/embedding_api/tests ./tests

CMD ["pytest", "-v", "/app/tests"]