name: ${COMPOSE_PROJECT_NAME}-test

services:

  ########################################################
  # Embedding API Test
  ########################################################

  embedding-api-test:

    build:
      context: ..
      dockerfile: services/embedding_api/Dockerfile.test

    container_name: ${EMBEDDING_CONTAINER_NAME}-test

    env_file:
      - ../config/app.env
      - ../config/rag.env

    volumes:
      - ../config:/app/config:ro
      - ../tests:/app/tests:ro
      - ../models:/models:ro

    depends_on:
      chromadb:
        condition: service_started

    networks:
      - ai-network

    command:
      - pytest
      - -v
      - /app/tests

  ########################################################
  # ChromaDB
  ########################################################

  chromadb:

    image: chromadb/chroma:1.0.15

    container_name: ${CHROMA_CONTAINER_NAME}-test

    volumes:
      - ../data/chromadb:/data

    networks:
      - ai-network

########################################################
# Networks
########################################################

networks:

  ai-network:

    name: ${DOCKER_NETWORK}-test

    driver: bridge
