FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1
ss
WORKDIR /app

COPY services/rag_api/requirements.txt .

COPY services/rag_api/requirements-test.txt .

RUN pip install --no-cache-dir \
    -r requirements.txt \
    -r requirements-test.txt

COPY services/rag_api/app ./app

CMD ["pytest", "-v", "/app/tests"]